config/routes.rb
Rails.application.routes.draw do

  get 'favorite/add/:id' => "favorite#add"

  get 'favorite/view'

  get 'cart/add'

  get 'cart/view'

  get 'cart/purchase'

  get '/' => "itempage#index"

  get 'items' => "itempage#index"

  get 'itempage/index' => "itempage#index"

  get 'item/:id/detail' => "itempage#show"

  post 'item/search' => "itempage#search"

  get 'category/:idlv1/:idlv2/:idlv3' => "category#show"
  get 'category/:idlv1/:idlv2' => "category#show"
  get 'category/:idlv1' => "category#show"

  post 'add_item_to_cart' => "cart#add"
  get 'create_user' => "application#create_user"

  mount Spree::Core::Engine, :at => '/'
          devise_for :users

  root to: "home#index"
  
  devise_scope :user do
    get '/login', :to => "devise/sessions#new"
    get '/signup', :to => "devise/registrations#new"
    delete '/logout', :to => "devise/sessions#destroy"
    get '/', :to => "devise/sessions#new"
  end

  match "*path", to: "application#wrong_request_url", via: :all
end

app/views/layouts/_category_nav.html.erb
<nav class="category-nav">
    <ul class="container">

    <% @category_menus.each do |category_menu| %>
        <li class="item"><a href="/category/<%= category_menu.category_id %>"><%=raw category_menu.category_name %></a>
        </li>
    <% end %>

    </ul>
</nav>

app/views/layouts/_top_header.html.erb
<div class="site-unit">
</div>

<div class="shopping-unit">
    <nav class="site-nav">
    </nav>

    <div class="cart-unit">
        <a href="/cart/view" class="in-cart">
            <div class="btn-blue-cart">
                <div class="check-cart">
                    <span>カートをみる</span>
                    <div class="btn-white-micro">  
                    <% 
                        review_cart = session["review_cart"] 
                        if review_cart.nil?
                            review_total_qty = 0
                            review_total_price = 0
                        else
                            review_total_qty = review_cart['total_qty']
                            review_total_price = review_cart['total_price']
                        end
                    %>

                        <p class="item-count"> <%= review_total_qty.to_i %>点</p>
                        <p class="item-price">合計
                            <span class="price">&yen;<%= review_total_price.to_i %></span>
                        </p>

                    </div>
                </div>
            </div>
        </a>
    </div>

    <nav class="shopping-nav">
        <ul class="container">
            <li class="item register"><a href="/create_user">新規会員登録</a>
            </li>
            <li class="item favorite"><a href="/favorite/view">お気に入り</a>
            </li>
            <li class="item history"><a href="/cart/purchase">購入履歴</a>
            </li>
        </ul>
    </nav>

    <div class="status">
        <div class="login-unit">
            <p class="greeting">こんにちは
                <span class="login-name">
                <%if @user.nil? %>
                        ゲスト
                    <% else %>
                        <%= @user.email %>
                    <% end %>
                </span>さま</p>
            <!-- <a href="#">
                <p class="btn-pink-micro">ログイン</p>
            </a> -->

        <% if spree_current_user %>
            <%= link_to raw("<p class='btn-pink-micro'>ログアウト</p>"), spree_logout_path, :method => :delete %>
        <% else %>
            <%= link_to raw("<p class='btn-pink-micro'>ログイン</p>"), spree_login_path %>
        <% end %>

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <!-- <title>TA-ShoppingSite</title> -->
  <title> <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="detail" class="home">
<div id="fb-root"></div>
<div id="wrapper">
<header>

    <div class="container">
        
        <%= render 'layouts/top_header' %>
        <%= render 'layouts/category_nav' if !@category_menus.nil?%>
        
    </div>

</header>
<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<!-- 
<%= debug(@item_features) if Rails.env.development? %>
 -->
</div>
</body>
</html>